// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/callback.tsx";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/login.tsx";
import * as $6 from "./routes/logout.tsx";
import * as $7 from "./routes/p/[id_with_host].tsx";
import * as $$0 from "./islands/Button.tsx";
import * as $$1 from "./islands/Counter.tsx";
import * as $$2 from "./islands/Folder.tsx";
import * as $$3 from "./islands/LoginForm.tsx";
import * as $$4 from "./islands/LogoutLogic.tsx";
import * as $$5 from "./islands/Mfm.tsx";
import * as $$6 from "./islands/MiAuthCallback.tsx";
import * as $$7 from "./islands/MisskeyPlaySearchBox.tsx";
import * as $$8 from "./islands/Monaco.tsx";
import * as $$9 from "./islands/NumberInput.tsx";
import * as $$10 from "./islands/Play.tsx";
import * as $$11 from "./islands/PlayDebugger.tsx";
import * as $$12 from "./islands/PostFormButton.tsx";
import * as $$13 from "./islands/RemotePlay.tsx";
import * as $$14 from "./islands/Switch.tsx";
import * as $$15 from "./islands/TextInput.tsx";
import * as $$16 from "./islands/Textarea.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/joke.ts": $2,
    "./routes/callback.tsx": $3,
    "./routes/index.tsx": $4,
    "./routes/login.tsx": $5,
    "./routes/logout.tsx": $6,
    "./routes/p/[id_with_host].tsx": $7,
  },
  islands: {
    "./islands/Button.tsx": $$0,
    "./islands/Counter.tsx": $$1,
    "./islands/Folder.tsx": $$2,
    "./islands/LoginForm.tsx": $$3,
    "./islands/LogoutLogic.tsx": $$4,
    "./islands/Mfm.tsx": $$5,
    "./islands/MiAuthCallback.tsx": $$6,
    "./islands/MisskeyPlaySearchBox.tsx": $$7,
    "./islands/Monaco.tsx": $$8,
    "./islands/NumberInput.tsx": $$9,
    "./islands/Play.tsx": $$10,
    "./islands/PlayDebugger.tsx": $$11,
    "./islands/PostFormButton.tsx": $$12,
    "./islands/RemotePlay.tsx": $$13,
    "./islands/Switch.tsx": $$14,
    "./islands/TextInput.tsx": $$15,
    "./islands/Textarea.tsx": $$16,
  },
  baseUrl: import.meta.url,
};

export default manifest;
