version: "3"

services:
  frontend:
    build:
      context: .
      args:
        GIT_REVISION: $(git rev-parse HEAD)
    environment:
      - host=http://localhost:8000/
    ports:
      - "8000:8000"